/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#f9f9f9",
        "surface-container-high": "#e8e8e8",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2f3131",
        "surface-dim": "#dadada",
        outline: "#6d7a77",
        "on-primary-container": "#f4fffc",
        "outline-variant": "#bcc9c6",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#773215",
        "surface-bright": "#f9f9f9",
        "surface-container": "#eeeeee",
        primary: "#00685f",
        "on-background": "#1a1c1c",
        "inverse-on-surface": "#f0f1f1",
        "secondary-container": "#d9dff5",
        "on-secondary-fixed": "#141b2b",
        "on-surface": "#1a1c1c",
        "surface-tint": "#006a61",
        "tertiary-container": "#b05e3d",
        "error-container": "#ffdad6",
        secondary: "#575e70",
        "on-primary-fixed": "#00201d",
        "on-primary-fixed-variant": "#005049",
        "on-secondary-fixed-variant": "#404758",
        "secondary-fixed-dim": "#c0c6db",
        "tertiary-fixed-dim": "#ffb59a",
        "on-tertiary-fixed": "#370e00",
        "on-tertiary-container": "#fffbff",
        "on-error-container": "#93000a",
        "inverse-primary": "#6bd8cb",
        "surface-container-highest": "#e2e2e2",
        "primary-fixed-dim": "#6bd8cb",
        "secondary-fixed": "#dce2f7",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#89f5e7",
        surface: "#f9f9f9",
        "on-surface-variant": "#3d4947",
        "tertiary-fixed": "#ffdbce",
        "surface-variant": "#e2e2e2",
        "on-secondary-container": "#5c6274",
        "primary-container": "#008378",
        error: "#ba1a1a",
        "surface-container-low": "#f3f3f3",
        tertiary: "#924628",
        navy: "#111827",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Plus Jakarta Sans", "sans-serif"],
      },
    },
  },
  plugins: [],
}
